### PR TITLE
Add data to .neuroignore

### PR DESCRIPTION
**Pull request by YevheniiSemendiak**
several folks asked about it: @johngull and one guy from the Synthesis team

### CODE REVIEW

**Comment by YevheniiSemendiak** [comment]
ping @anayden

**Comment by anayden** [comment]
Hey, I did make progress on testing, but haven't completed it yet, sorry :( Looks good so far (aside from the sharing issues we discussed yesterday).
I'm now working on a fix for buckets as it seems to be more urgent and will switch back to the PR asap

**Comment by YevheniiSemendiak** [comment]
Hey mate! You're completely right, buckets are of the highest priority, no rush here.
This isn't bones project, therefore I've decided to ping you since this tiny pr could pass you by.

**Comment by anayden** [comment]
oops, you're right — i thought you pinged me on the bones project. sorry. approving this one immediately :)

**Review by anayden — APPROVED** [review]

**Pull request merged**
